name: Build & test package

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.10', '3.11', '3.12']
    env:
      MPLBACKEND: Agg  # https://github.com/orgs/community/discussions/26434
    steps:
      - uses: actions/checkout@v3
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Python info
        run: |
          uv python find
          uv --version
      - name: Install dependencies
        run: |
          uv pip install --upgrade ".[all]" # MONET-MonetDB
          uv pip install pre-commit pytest
      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files
      - name: Run tests
        run: uv run pytest
